---
title: Crystal Camarao
timezone: Asia/Hong_Kong
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author:
  name: Crystal Camarao
  email: me@crystal.ph
description: Personal blog of Crystal Camarao
show_excerpts: true
minima:
  date_format: "%b %-d, %Y"
  skin: modified
  social_links:
    twitter: crystalcamarao
    github: crystalcamarao
    linkedin: crystalcamarao
    telegram: crystalcamarao
theme: minima
plugins:
- jekyll-feed
- jekyll-seo-tag
google_analytics: UA-81646954-2
header_pages:
- about.md
- side-projects.html
facebook_app_id: 386459599144650
