---
title: Personal blog of Crystal Camarao
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author:
  name: Crystal Camarao
  email: hello@crystal.ph
description: 'Thoughts on web design, digital marketing, and everything in between.

'
show_excerpts: true
minima:
  date_format: "%b %-d, %Y"
  skin: modified
  social_links:
    twitter: crystalcamarao
    github: crystalcamarao
    linkedin: crystalcamarao
    telegram: crystalcamarao
theme: minima
google_analytics: UA-81646954-2
plugins:
- jekyll-feed
- jekyll-seo-tag
